# Generated by Django 4.1.13 on 2023-11-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregistrationmodel',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
    ]
