# Generated by Django 4.1.13 on 2023-12-06 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=100)),
                ('phone', models.BigIntegerField(null=True)),
                ('address', models.CharField(default='', max_length=400)),
            ],
            options={
                'verbose_name': 'UserRegistration',
                'verbose_name_plural': 'UserRegistrations',
            },
        ),
        migrations.CreateModel(
            name='BookDoctorModel',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('doctorid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_app.doctorregistrationmodel')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.userregistration')),
            ],
            options={
                'verbose_name': 'BookDoctorModel',
                'verbose_name_plural': 'BookDoctorModels',
            },
        ),
    ]
