# Generated by Django 4.1.13 on 2024-01-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultsmodel',
            name='rhFactor',
        ),
    ]
