# Generated by Django 4.1.13 on 2024-02-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmimodel",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="predictionmodel",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
