# Generated by Django 4.1.13 on 2023-11-29 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdoctormodel',
            name='id',
        ),
        migrations.AddField(
            model_name='bookdoctormodel',
            name='bookingid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookdoctormodel',
            name='doctorid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_app.doctorregistrationmodel'),
        ),
        migrations.AddField(
            model_name='bookdoctormodel',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.userregistration'),
        ),
    ]
