# Generated by Django 4.1.13 on 2023-12-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultsmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='resultsmodel',
            name='resultid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultsmodel',
            name='cholesterol',
            field=models.IntegerField(blank=True, help_text='Cholestrol', null=True),
        ),
        migrations.AlterField(
            model_name='resultsmodel',
            name='redBloodCells',
            field=models.IntegerField(blank=True, help_text='RBC 4.35 to 5.65 (mcL)', null=True),
        ),
        migrations.AlterField(
            model_name='resultsmodel',
            name='serumLeucocytes',
            field=models.IntegerField(blank=True, help_text='leukocytes (adults and children >2 years) - 5000-10,000/mm', null=True),
        ),
        migrations.AlterField(
            model_name='resultsmodel',
            name='testDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultsmodel',
            name='whiteBloodCells',
            field=models.IntegerField(blank=True, help_text='WBCs in the blood is 4,500 to 11,000 WBCs per microliter', null=True),
        ),
    ]
