# Generated by Django 4.1.13 on 2024-02-04 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdoctormodel',
            name='doctorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_app.doctorregistrationmodel'),
        ),
        migrations.AlterField(
            model_name='bookdoctormodel',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='user_app.userregistrationmodel'),
        ),
    ]
