# Generated by Django 4.1.13 on 2024-02-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0002_alter_bookdoctormodel_doctorid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultsmodel",
            name="cost",
            field=models.IntegerField(
                blank=True, help_text="Cost of checking", null=True
            ),
        ),
    ]
