# Generated by Django 4.1.13 on 2024-01-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_resultsmodel_rhfactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultsmodel',
            name='redBloodCells',
        ),
        migrations.RemoveField(
            model_name='resultsmodel',
            name='serumLeucocytes',
        ),
        migrations.RemoveField(
            model_name='resultsmodel',
            name='uricAcid',
        ),
        migrations.RemoveField(
            model_name='resultsmodel',
            name='whiteBloodCells',
        ),
    ]
