# Generated by Django 4.1.13 on 2024-02-22 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0003_resultsmodel_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicinesmodel",
            name="med_status",
        ),
    ]
