# Generated by Django 4.1.13 on 2024-01-05 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_resultsmodel_redbloodcells_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinesmodel',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='user_app.userregistrationmodel'),
        ),
        migrations.AlterField(
            model_name='resultsmodel',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='user_app.userregistrationmodel'),
        ),
    ]
