# Generated by Django 4.1.13 on 2024-02-25 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0004_remove_medicinesmodel_med_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationsModel",
            fields=[
                (
                    "notification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("status", models.BooleanField(blank=True, null=True)),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="message for the user",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_app.userregistrationmodel",
                    ),
                ),
            ],
        ),
    ]
