# Generated by Django 4.1.13 on 2024-02-25 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0005_notificationsmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationsmodel",
            old_name="status",
            new_name="noti_status",
        ),
    ]
