# Generated by Django 4.1.13 on 2024-02-27 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0006_rename_status_notificationsmodel_noti_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionModel",
            fields=[
                (
                    "notification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("age_of_user", models.FloatField(blank=True, null=True)),
                ("sex", models.FloatField(blank=True, null=True)),
                ("cp", models.FloatField(blank=True, null=True)),
                ("trestbps", models.FloatField(blank=True, null=True)),
                ("chol", models.FloatField(blank=True, null=True)),
                ("fbs", models.FloatField(blank=True, null=True)),
                ("restecg", models.FloatField(blank=True, null=True)),
                ("thalach", models.FloatField(blank=True, null=True)),
                ("exang", models.FloatField(blank=True, null=True)),
                ("oldpeak", models.FloatField(blank=True, null=True)),
                ("slope", models.FloatField(blank=True, null=True)),
                ("ca", models.FloatField(blank=True, null=True)),
                ("thal", models.FloatField(blank=True, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_app.userregistrationmodel",
                    ),
                ),
            ],
        ),
    ]
