# Generated by Django 4.1.13 on 2024-02-27 06:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0010_rename_age_of_user_predictionmodel_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bmimodel",
            name="bmi",
        ),
    ]
